[program:meeting-room-queue]
process_name=%(program_name)s
command=/www/server/php/82/bin/php /www/wwwroot/meeting.sisuu.com/backend/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
directory=/www/wwwroot/meeting.sisuu.com/backend
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwlogs/meeting-room-queue.log
stopwaitsecs=3600

[program:meeting-room-api]
process_name=%(program_name)s
command=/www/server/php/82/bin/php /www/wwwroot/meeting.sisuu.com/backend/artisan serve --host=127.0.0.1 --port=8000
directory=/www/wwwroot/meeting.sisuu.com/backend
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwlogs/meeting-room-api.log
